import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center justify-center py-6 bg-white/80 backdrop-blur border-b border-gray-200 mb-8 sticky top-0 z-50">
          <div className="flex gap-8 text-lg font-medium text-gray-800">
            <a href="/" className="hover:text-blue-600 transition-colors">Home</a>
            <a href="/about" className="hover:text-blue-600 transition-colors">About</a>
            <a href="/services" className="hover:text-blue-600 transition-colors">Services</a>
            <a href="/music" className="hover:text-blue-600 transition-colors">Music</a>
            <a href="/socials" className="hover:text-blue-600 transition-colors">Socials</a>
            <a href="/contact" className="hover:text-blue-600 transition-colors">Rhythmi</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
